package engine;

import model.Requirement;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

public class TraceabilityReporter {

    public void generateMarkdownReport(List<Requirement> requirements, String fileName) {
        try (PrintWriter writer = new PrintWriter(new FileWriter(fileName))) {
            writer.println("# Aegis-X Traceability and Validation Report");
            writer.println("Generated by ReqTrace-Java - Systems Engineering Analysis Tool\n");
            
            writer.println("## Executive Summary");
            long compliantCount = requirements.stream().filter(Requirement::isCompliant).count();
            writer.println("- Total Requirements Analyzed: " + requirements.size());
            writer.println("- Formal Compliance Rate: " + (compliantCount * 100 / requirements.size()) + "%");
            writer.println("\n---");

            writer.println("## Requirements Analysis Matrix");
            writer.println("| ID | Subsystem | Compliance | Impact | Complexity | Requirement Text |");
            writer.println("| :--- | :--- | :--- | :--- | :--- | :--- |");

            for (Requirement r : requirements) {
                String status = r.isCompliant() ? "Valid" : "Non-Compliant";
                writer.println(String.format("| %s | %s | %s | %s | %s | %s |", 
                               r.getId(), r.getSubsystem(), status, r.getImpactLevel(), r.getComplexityStatus(), r.getText()));
            }

            writer.println("\n");
            appendMermaidDiagram(writer, requirements);

            writer.println("\n## Risk Assessment");
            if (compliantCount < requirements.size()) {
                writer.println("Warning: System contains non-compliant formal language. High risk for certification.");
            } else {
                writer.println("Success: All requirements meet formal engineering standards.");
            }
        } catch (IOException e) {
            System.err.println("Error writing report: " + e.getMessage());
        }
    }

    private void appendMermaidDiagram(PrintWriter writer, List<Requirement> requirements) {
        writer.println("## System Architecture Visualization");
        writer.println("```mermaid");
        writer.println("graph TD");
        writer.println("    System[Aegis-X Missile System] --- Nav[Navigation]");
        writer.println("    System --- Prop[Propulsion]");
        writer.println("    System --- Safe[Safety]");
        writer.println("    System --- Comm[Communication]");
        
        for (Requirement r : requirements) {
            String shortSub = r.getSubsystem().length() > 4 ? r.getSubsystem().substring(0, 4) : r.getSubsystem();
            writer.println(String.format("    %s --> %s(%s)", shortSub, r.getId(), r.getId()));
        }
        writer.println("```");
    }

    public void exportToJson(List<Requirement> requirements, String fileName) {
        try (PrintWriter writer = new PrintWriter(new FileWriter(fileName))) {
            writer.println("[");
            for (int i = 0; i < requirements.size(); i++) {
                Requirement r = requirements.get(i);
                writer.println("  {");
                writer.println("    \"id\": \"" + r.getId() + "\",");
                writer.println("    \"subsystem\": \"" + r.getSubsystem() + "\",");
                writer.println("    \"compliance\": " + r.isCompliant() + ",");
                writer.println("    \"impact\": \"" + r.getImpactLevel() + "\",");
                writer.println("    \"complexity\": \"" + r.getComplexityStatus() + "\"");
                writer.print("  }" + (i < requirements.size() - 1 ? "," : ""));
                writer.println();
            }
            writer.println("]");
        } catch (IOException e) {
            System.err.println("Error exporting JSON: " + e.getMessage());
        }
    }
}